### ISSUE TITLE
annual_rainfall_summaries returns errors when bring back all summaries

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#44]
params: 
{
  "country": "zm",
  "station_id": "01122",
  "summaries": [
    "annual_rain",
    "start_rains",
    "end_rains",
    "end_season",
    "seasonal_rain",
    "seasonal_length"
  ]
}

error message: 
Error in (function (country, station_id, summaries = c(\"annual_rain\",  : \n  Missing value in end_season definitions for start_day.\n"

**Comment by lilyclements** [comment]
So the error says "Missing value in end_season definitions for start_day.".
This means that when we run `end_season`, we are not giving the value for the `start_day` parameter. As a result, it throws an error.

If you look at the definition file for 01122 you'll see that we only have definitions for `"annual_rain"`, `"start_rains"`, `"end_rains"`.
This means that the code cannot run because there are no definitions given for the end_season. Hence, it does not know what "start_day" is (should be 121 I think)

```
# To look at the definitions data: 
epicsadata::get_definitions_data(country = "zm", station_id = "01122")
```

**Comment by ChrisMarsh82** [comment]
Closing as there are still issues with data but that is covered in #94
