### ISSUE TITLE
annual_rainfall_summaries cannot return seasonal_rain or seasonal_length on their own.

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#45]
Params: 
{
  "country": "zm",
  "station_id": "test_1",
  "summaries": [
    "seasonal_rain"
  ]
}
error: Error in (function (country, station_id, summaries = c(\"annual_rain\",  : \n  start_rains and at least one of end_season or end_rains is required to calculate seasonal_rain\n"

and 
Params: 
{
  "country": "zm",
  "station_id": "test_1",
  "summaries": [
    "seasonal_length"
  ]
}
error: Error in (function (country, station_id, summaries = c(\"annual_rain\",  : \n  start_rains and at least one of end_season or end_rains is required to calculate seasonal_length\n"

Both requests work if all the summaries are added.

**Comment by lilyclements** [comment]
@ChrisMarsh82 this is working as I expected it to work

To get seasonal_anything, then we need to have the start and end of the season
* Start of season: Calculated by the start_rains option
* End of season: Calculated by either end_rains or end_season.

> Both requests work if all the summaries are added.

If all the summaries are added, then the start and end dates are calculated and so the seasonal bits can be calculated. We need to have the start and end bits there which is why it throws the error.

**Comment by ChrisMarsh82** [comment]
@lilyclements but why can't it calculate that in the background? Why would I need to request more summaries? I am only interested in the start_rains, not anything else.

**Comment by lilyclements** [comment]
If you want just start of rains it should work. If you want anything with seasons then the code needs to know the start and ends date for the season (otherwise how can we get the seasonal length or rainfall amounts). So you need to give definitions for how you want to define your start and end of season to get the seasonal summaries.

**Comment by ChrisMarsh82** [comment]
@lilyclements I understand that but I am not sending any more information by requesting more summaries. Although it needs the other summaries it should be a valid request to just ask for each summary individually. 
The code should be able to deal with each summary individually or any combination.

**Comment by lilyclements** [comment]
@ChrisMarsh82 sure. From previous discussions we decided to not have this work if there’s no parameters read in for the others but I don’t mind.
So what should we set as the default options for the start_rains?
And do we do end rains or end season by default?
I’ll add a warning in so that the user knows that these seasonal values are based on the default summaries.

**Comment by lilyclements** [comment]
fixed by #62

**Comment by lilyclements** [comment]
Leaving this for you to check and close @ChrisMarsh82
