### ISSUE TITLE
data definition returned inconsistently for station 01122, annual_rain in annual_rainfall_summaries

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#46]
params:
{
  "country": "zm",
  "station_id": "01122",
  "summaries": [
    "annual_rain"
  ]
}

This returns data however, **"data":"station_name"** has become **"data":"station"** this is inconsistent as if the same request is done for station: test_1 then **"data":"station_name"** is returned.

**Comment by lilyclements** [comment]
@ChrisMarsh82 the reason for this is that the 01122 data is dummy data. In here, our station variable is called "station", whereas in the other data it is called "station_name". This is good as it means that it is working regardless of the name of our station variable.

```
epicsadata::get_daily_data(country = "zm", station_id = "01122")  # variable called station
epicsadata::get_daily_data(country = "zm", station_id = "test_1")  # variable called station_name
```

I would assume to not confuse the user, we wouldn't want to rename their variables to fit our format, but instead keep it called their name. (e.g. they might have something in another language)

**Comment by ChrisMarsh82** [comment]
@chrismclarke Is this an issue? Does the station_name need to be consistent? Is it ok to be 'station' or 'station_name'?

**Comment by chrismclarke** [comment]
The python layer includes typed definitions for the api endpoints, using models to specify the expected shape of data. The models are defined as classes which extend a [Pydantic Model](https://docs.pydantic.dev/latest/concepts/models/) base

I'm pretty sure when passing data to these models an error will be thrown if it does not conform, so yes a different between `station` and `station_name` will result in an  internal server error when exposed through the api. So ideally we want the R layer to be entirely consistent, or failing that the python layer to correctly map to a consistent model.

However as of now I can see most of the endpoints only use models to define input parameters, and not the return response objects, so these should also be updated otherwise descrepencies may slip through.

**Comment by lilyclements** [comment]
Leaving this for you to check and close @ChrisMarsh82
