### ISSUE TITLE
annual_temperature_summaries issues

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#96]
- [x] test_1 - despite defining min_tmin, min_tmax, max_tmin, max_tmax only the means come back
- [x] #95 
- [x] station 1 - not sure if this is right but for 1949 and 1950 we get null. Is the entire year of data missing? also 2015 we get tmax results but not tmin

**Comment by lilyclements** [comment]
@ChrisMarsh82 I've mentioned when making these changes that we now have an `override = FALSE` by default. I suspect a lot of issues you mention may be because of the `override = FALSE` by default, so it is calling the saved summaries by default. This means that the changes to the definitions file are not being read in.

1. This is because by default `override = FALSE`, so it is calling the **saved summary data**. Try running with `override = TRUE`. 
E.g.
```
epicsawrap::annual_temperature_summaries("zm", "test_1", override = TRUE)
```
2. See 1.
3. `na.rm = TRUE` is not read in. I will look at this here and elsewhere.
